stages:
  - check

variables:
  NODE_VERSION: "20.11.0"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^main$|^develop$|^feature\/.*$|^bug\/.*$/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

check_job:
  stage: check
  image: node:${NODE_VERSION}
  script:
    - npm ci
    - npx eslint .
    - npx prettier --write .
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/